### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by shrhops** [nterhoeven/blast2bed#3]
Hi, I'm using this tool as part of my thesis and wondering how I can cite it?

**Comment by nterhoeven** [comment]
Hi @shrhops 

nice to hear, you find it useful :smiley: 

There is no paper or similar that can be cited. I would use something like this (maybe adapted to your citation style):

> blast2bed, Niklas Terhoeven 2015, https://github.com/nterhoeven/blast2bed

**Comment by shrhops** [comment]
Great, thanks for the information!
